### PR TITLE
Another attempt at Python 3 support

### PR DESCRIPTION
**Pull request by jni**
I mostly copied @sdh4's patch from [here](https://github.com/CellProfiler/python-javabridge/issues/54#issuecomment-120068538) manually, since it didn't apply to the current master.

Fingers crossed that Travis likes it!

### CODE REVIEW

**Comment by jni** [comment]
=( Well, I'm past the easy fixes... Perhaps this will also languish... @sdh4 any ideas?

**Comment by sdh4** [comment]
I was never able to get the testing framework figured out.... That said, it seemed to actually run just fine. 

The JavaExceptions look like the Java side is not finding the classes. Those are probably pretty tricky, but they seem to occur under Python 2.7 also (?). 

A bunch of the failures part way down are very trivial: 
longs and ints have been merged into the single 'int' type. 

I would do something like
`try: 
    import builtins  # python3
    pass
except ImportError: 
    import __builtin__ as builtins # python2
    pass
    
if not hasattr(builtins,"long"):
    long=int  # python3
`

dict.iteritems() can probably be safely converted to dict.items() -- I don't think any of the cases here involve dictionaries that would be particularly large, the situations that suggest iteritems() over items() for Python 2.

**Comment by jni** [comment]
@sdh4 Thanks so much for your help! Hopefully someone from the core team can help me squash the less obvious bugs that are repeated between Python versions, but this keeps me moving. =)

**Comment by LeeKamentsky** [comment]
Let me put some time into this today. It looks like you guys have moved things along nicely and maybe it can get finished up with a little effort.

**Comment by jni** [comment]
Woot! =D

**Comment by LeeKamentsky** [comment]
WTG, @jni @sdh4 thanks for your help.

**Pull request merged**
