### PR TITLE
Attempt to add Travis CI support

### PR DESCRIPTION
**Pull request by jakirkham**
Want to see how this goes before comments, will remove WIP once ready.

The idea here is to install dependencies using [`conda`]( http://conda.pydata.org/docs/ ). This will give us `numpy` without too much work. The only trick will be to make sure that we get `javabridge` working.

### CODE REVIEW

**Comment by jakirkham** [comment]
@LeeKamentsky, this one has run up against a snag. It complains some file is missing. I have no idea. If you don't mind taking a look, maybe this could be fixed.

**Comment by LeeKamentsky** [comment]
See f552b3239208c4db6e9c20de81ac07dc49d15221 - need to install Cython. I'm guessing that you can proceed from there.

**Comment by jakirkham** [comment]
I was wondering if that was the case, but I saw somewhere in the code that `setuptools` was smart enough to pick up on this. Is this not true?

Also, the line it is failing only seems to reference Java files. Is there something else going on here that I am not following?

**Comment by LeeKamentsky** [comment]
I went down a rabbit-hole of trying fix the `jar` command, finally found out that it was the Cython by inserting lots of logging statements. The `jar` command completes successfully, but the Cython command fails here: https://github.com/CellProfiler/python-javabridge/blob/master/setup.py#L63

**Comment by LeeKamentsky** [comment]
Very close - it looks like the javabridge nose plugin isn't loading the test.jar.

**Comment by jakirkham** [comment]
As you already know, Cython did help get through the build. However, I am getting a few test failures. It also appears that the wrong Python library is being linked against ( `/usr/lib/x86_64-linux-gnu/libpython2.7.so` ). As this shouldn't even appear on the VM, I am guessing that this comes from something that is already linked against it (probably for an easier install?). I can drop the container and the link the system library to use `conda`'s `libpython2.7.so`. It might work. :/

**Comment by LeeKamentsky** [comment]
libpython2.7.so is probably being loaded by org.cellprofiler.javabridge.CPython inside the JVM. This lets you call Python from Java. javabridge/jars/java2cpython.so should be linked against it.

**Comment by jakirkham** [comment]
Ok, that workaround won't do it.

This appears to be the responsible line ( https://github.com/CellProfiler/python-javabridge/blob/c0301c16a0044fbfbf9747e14a60cc4e1f1fcaff/java/org_cellprofiler_javabridge_CPython.c#L70 ). If you already have the location of the current Python interpreter, this will give you the correct version of `libpython.X.Y.so`. It looks like there are similar things already happening in that code anyways.

    python -c "from distutils.sysconfig import get_config_var; from os.path import join; print(join(get_config_var(\"LIBDIR\"), get_config_var(\"LDLIBRARY\")))"

**Comment by LeeKamentsky** [comment]
Ouch - that code looks like I got it working on whatever computer I was using for testing, then forgot to do the right thing. It's a bug (#59), but it should not affect the tests.

**Comment by jakirkham** [comment]
No worries, I added a patch that will fix that bug here. It works on my Mac and it doesn't make testing go any worse on Travis. Unfortunately, you are correct, it doesn't fix the test failures.

**Comment by jakirkham** [comment]
Broke out that fix and put it in #60.

**Comment by jakirkham** [comment]
So, @LeeKamentsky, I don't think I will be able to solve this on my own. I think I will need some more pointers. I have created a docker container that reproduces the issues seen in the test suite. Here it is ( https://hub.docker.com/r/jakirkham/javabridge/ ). I think this will just be faster while we are still trying to figure out why it is failing.

**Comment by LeeKamentsky** [comment]
I think I might take a shot at it. I'll see if I can make it work in that docker.

**Comment by LeeKamentsky** [comment]
My fork of the add_travis branch is building now and running the tests - hope this is OK, not the world expert on these things: https://github.com/LeeKamentsky/python-javabridge/commit/fff5c290a23c191caf3b8b9421ffe45da88c2d0f

**Comment by jakirkham** [comment]
That's fine. I just have a feeling that there might be something weird going on in build and being able to inspect directly might help.

**Comment by jakirkham** [comment]
@LeeKamentsky, you were correct. It needed to be installed in development mode. However, I can't say I understand why. Is there something different being done in the case of development install vs. a regular install?

**Comment by jakirkham** [comment]
Also, I have tagged on info to measure coverage from this package and submit it to coveralls. This works and I have done so with my fork.

**Comment by LeeKamentsky** [comment]
I think that Python gets confused when you run the nosetests from the git clone root directory. `python setup.py install` must be installing the .so files and jars in site-packages/javabridge, but when you start up nosetests, `import javabridge` doesn't load stuff from site-packages/javabridge, it loads it from ./javabridge and everything probably goes downhill after that. It's my guess, may be wrong.

**Comment by jakirkham** [comment]
Fair enough, in any case, I think this is ready to go. I remove the `java/org_cellprofiler_javabridge_CPython.c` patch from here. This only contains what is necessary to get testing to work.

**Comment by LeeKamentsky** [comment]
Thx for hanging in there. This is great.

**Comment by jakirkham** [comment]
That was fast. :)

**Pull request merged**
