### PR TITLE
Fixes #72 prevent call to getField for random attributes

### LINKED ISSUE #72: Use of wrapper classes in ipython causes Java Exceptions
Running the following code in ipython leads to a java exception
```
import javabridge
javabridge.start_vm(run_headless=True)
a = javabridge.JWrapper(javabridge.make_instance("java/util/ArrayList","()V"))
a
```

I would hope that `a` on its own would call the __repr__ method and show the array but instead it give a java exception:

```
Exception in thread "Thread-1" java.lang.NoSuchFieldException: _ipython_display_
        at java.lang.Class.getField(Class.java:1690)
Out[4]: Instance of java.util.ArrayList: []
```

A user-defined class without _ipython_display_ defined works as expected. I'm not sure where the problem lies but the ability to wrap Java classes in python in an interactive session is awesome and it would be worth getting it working nicely.

I've posted a parallel issue on ipython as I'm not sure where changes need making: https://github.com/ipython/ipython/issues/9253

### PR DESCRIPTION
**Pull request by LeeKamentsky**
@jbcoe can you review and if it works for you, I will merge?

### CODE REVIEW

**Comment by jbcoe** [comment]
I'm unable to build this package on OS X or Ubuntu (previously I used pip to install it).
The error I get is the same on OS X and Linux:
```
$ python setup.py build

/usr/local/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('1.0.11-28-ge295de4') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running build
running build_py
running build_ext
javac -source 6 -target 6 java/org/cellprofiler/runnablequeue/RunnableQueue.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
javac -source 6 -target 6 java/org/cellprofiler/javabridge/test/RealRect.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
javac -source 6 -target 6 java/org/cellprofiler/javabridge/CPython.java java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
error: [Errno 2] No such file or directory
```

I hava Java 8 installed:

```
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```

**Comment by LeeKamentsky** [comment]
If you used pip successfully, perhaps:

    pip uninstall javabridge
    pip install -e .

might work?

**Comment by jbcoe** [comment]
A similar error, perhaps more information this time:

```
Obtaining file:///private/tmp/python-javabridge
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/site-packages (from javabridge===1.0.11-28-ge295de4)
Installing collected packages: javabridge
  Running setup.py develop for javabridge
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/tmp/python-javabridge/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    /usr/local/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('1.0.11-28-ge295de4') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running develop
    running egg_info
    writing requirements to javabridge.egg-info/requires.txt
    writing javabridge.egg-info/PKG-INFO
    writing top-level names to javabridge.egg-info/top_level.txt
    writing dependency_links to javabridge.egg-info/dependency_links.txt
    writing entry points to javabridge.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'javabridge.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '_javabridge.c'
    warning: no files found matching '_javabridge_mac.c'
    warning: no files found matching '_javabridge_nomac.c'
    no previously-included directories found matching '*.pyx'
    writing manifest file 'javabridge.egg-info/SOURCES.txt'
    running build_ext
    javac -source 6 -target 6 /private/tmp/python-javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    jar cf /private/tmp/python-javabridge/javabridge/jars/runnablequeue.jar -C /private/tmp/python-javabridge/java org/cellprofiler/runnablequeue/RunnableQueue$1.class -C /private/tmp/python-javabridge/java org/cellprofiler/runnablequeue/RunnableQueue.class
    javac -source 6 -target 6 /private/tmp/python-javabridge/java/org/cellprofiler/javabridge/test/RealRect.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    1 warning
    jar cf /private/tmp/python-javabridge/javabridge/jars/test.jar -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/test/RealRect.class
    javac -source 6 -target 6 /private/tmp/python-javabridge/java/org/cellprofiler/javabridge/CPython.java /private/tmp/python-javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
    warning: [options] bootstrap class path not set in conjunction with -source 1.6
    Note: /private/tmp/python-javabridge/java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    1 warning
    jar cf /private/tmp/python-javabridge/javabridge/jars/cpython.jar -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/CPython$StackFrame.class -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/CPython$WrappedException.class -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/CPython.class -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/CPythonInvocationHandler.class -C /private/tmp/python-javabridge/java org/cellprofiler/javabridge/CPythonInvocationHandler.class
    error: [Errno 2] No such file or directory
```

I get the same error from the master branch.

**Comment by jbcoe** [comment]
Installing cython fixed the install issues.

javabridge now works very nicely with ipython.

Thanks for your awesome library and rapid turnaround. I look forward to making use of javabridge.

**Pull request merged**
